### ISSUE TITLE
Name Customization: Not possible to use logic (concat string, helper functions etc.)

### ISSUE THREAD

**Issue by ttristan** [tajo/ladle#124]
**Is your feature request related to a problem? Please describe.**
I would like to streamline story namespaces using the [Name Customization feature](https://ladle.dev/docs/stories#name-customization). However, it does not seem to be possible to use any logic exporting a story title. 

Doing so a blank page is shown an I get this error in the browser console:
> Uncaught SyntaxError: The requested module '/generated/generated-list.tsx' does not provide an export named 'storySource' (at source.tsx:6:1)

**Working Example:**
```
export default {
    title: 'Core / Button',
};
```

**Broken Exmaples:** 
```
export default {
    title: 'Core' + ' / ' + 'Button',
};

or 

export default {
    title: `${'Core'} / ${'Button'}`,
};
```

My usecase:
```
// utils.ts
const getStoryName = (namespace: 'Core' | 'Features', componentName: string) =>
    `${namespace} / ${componentName}`;

// button.story.ts
export default {
    title: getStoryName('Core', 'Button'),
};
```

**Comment by tajo** [comment]
Story names need to be static (simple strings). It's the intentional limitation of Ladle to support automatic code-splitting and some other features.  It seems there might be some regression in the error message that's makes it unclear - should look into it. Also, we should probably highlight this more in the docs.
