### ISSUE TITLE
Laddle won't load images from the public folder

### ISSUE THREAD

**Issue by maksimf** [tajo/ladle#204]
**Describe the bug**

I'm using nextjs and I have a bunch of images in my public folder (which is locatied on the same level as my src) and when I try to load it ladle returns 404

**Reproduction**

```
<img src="/logo.svg />
```

returns 404 in ladle stories

**Environment**

 - OS: Linux
 - Browser: Chrome

**Comment by tajo** [comment]
You can configure it: https://vitejs.dev/config/shared-options.html#publicdir

However, we should add it our base config. It needs the same treatment as [`envDir`](https://github.com/tajo/ladle/blob/master/packages/ladle/lib/cli/vite-base.js#L94) - set to process.cwd()/public if not specified by user since Ladle's Vite root is inside of `node_modules`.

**Comment by tajo** [comment]
should be fixed
