### ISSUE TITLE
Failed to compile with error when trying to use a 3rd party data generator file like "namorjs"

### ISSUE THREAD

**Issue by jcleefw** [tajo/ladle#256]
**Describe the bug**

When trying to use a library like [namor.js](https://github.com/jsonmaur/namor) to generate mock data, story fail to compile throwing issues about `crypto.randomBytes` inaccessible

![Screen Shot 2022-08-31 at 10 55 12 am](https://user-images.githubusercontent.com/4728185/187569486-7ab908e0-ce4f-4de9-992d-789756b487b6.png)

It's not necessary about using `Namor.js`. I'm happy to use any library, but given that `crypto.randomBytes` is part of a Node.js, I think it might be necessary to look into the issue

**Reproduction**

**_See the stackblitz -> Controls.tsx story._**
https://stackblitz.com/edit/ladle-5uhk6y?file=package.json,src%2Fcontrols.stories.tsx

**Environment**

 - OS: IOS
 - Browser: chrome
 - Version: 104.0.5112.101 (Official Build) (x86_64)

**Comment by tajo** [comment]
> I'm happy to use any library, but given that crypto.randomBytes is part of a Node.js, I think it might be necessary to look into the issue

So why would you expect it to work in browser (as a part of story)?

**Comment by jcleefw** [comment]
i think it's use case that might happen where user uses library to generate mock data for a story. I've use the same library in Storybook to do things like that and it's working as expected.

**Comment by tajo** [comment]
It probably works in Storybook because Webpack 4 polyfills `crypto` out of the box (removed in Webpack 5).

You can attempt [resolve.alias](https://vitejs.dev/config/shared-options.html#resolve-alias) `crypto` to something like `crypto-browserify` but I would strongly recommend avoiding this altogether and just using some other library that's built for browsers.
