### ISSUE TITLE
Asking for permissions on MacOS

### ISSUE THREAD

**Issue by matheusgrieger** [tajo/ladle#259]
Is it normal for this library to ask for Finder and other permissions on MacOS? That's the first time I see it happening so I was wondering if it is expected or not. At first I allowed Finder and refused the second one (which I don't remember what it was but it was some Apple service), and then running on another terminal I got asked for permissions again but refused for Finder and it worked both times.

**Comment by tajo** [comment]
Yea, (afaik) it happens when we look for the default browser setting using: https://github.com/sindresorhus/default-browser

Without this, we can't have both of these on Mac:
- automatically try to re-use a tab in Chrome *only* if Chrome is the default browser
- automatically open the default browser

For long time, we have been ignoring the default browser and always tried to reuse a tab in Chrome if possible and only after that defaulting to the system browser but some folks not happy about it: https://github.com/tajo/ladle/issues/224

If this permission thing is too spooky might revert back to that. :/

**Comment by matheusgrieger** [comment]
That's the thing, it still worked without giving any permissions. And also does CRA, it behaves just like that without asking for extra permissions. It got me a little startled I must say, but if that's expected then no problem. Maybe add that to the docs?

**Comment by tajo** [comment]
I'll probably just remove the default browser functionality. You can set the browser through the ENV variable.

**Comment by matheusgrieger** [comment]
Thank you for clarifying!
