### ISSUE TITLE
Vite reloads on story change

### ISSUE THREAD

**Issue by snowytime** [tajo/ladle#302]
**Describe the bug**

If your '*.stories' file has a default export, it will break hmr on every save.

**Reproduction**

Just make a story with a default export and start editing stories, vite does a full update-invalidation-reload cycle for every change. Now comment out the default export and do the same thing, hmr works again 

Not sure if this is intended behaviour but kinda weird :/

**Comment by tajo** [comment]
Hm, I think it's an expected behavior in the current implementation of react-refresh and Vite's React plugin. I believe there is a check that opt-outs of HMR if all exports are not React components. (Also, we do full reload when templates / .bind() syntax is used for similar reasons).

It might be possible to do something custom (an exception to this rule for stories). On the other hand, `export default` is optional in Ladle. Also, stories typically load code from other files/modules and most of day-to-day work happens there. In that case the HMR would work since you are not modifying `.stories.` files directly.

**Comment by tajo** [comment]
You could probably replicate this behavior in any modern React framework that uses HMR.

**Comment by snowytime** [comment]
@tajo that makes alot of sense, and yeah Vite does the hard reloads if anything other than react is exported (interfaces, types, etc.) so this is a vite thing for sure and thanks for the info !!
