### ISSUE TITLE
Title "must be a string literal."

### ISSUE THREAD

**Issue by xseman** [tajo/ladle#95]
`title` and `component.storyName` doesn't allow to be set as variable.

```typescript
const foo = 'Level / Sub level';

export default {
    title: foo,
    // Error: Can't parse the default title and meta of src/basic.stories.tsx. 
    // Meta must be serializable and title a string literal.
};

export const Button = () => <button>My Button</button>;

// Button.storyName = foo;
// Error: Button.storyName in src/basic.stories.tsx must be a string literal.
```

https://stackblitz.com/edit/ladle-bp6tgk?file=src%2Fbasic.stories.tsx

**Comment by tajo** [comment]
Correct. This is a built in limitation - the title needs to be a string literal since because we parse/extract it during the build time. Should probably mention that in the docs somewhere.

**Comment by xseman** [comment]
I want to create custom tree structure based on actual file path. Inspirated from [storybook][1]
Any plan for this type of feature? Thanks!

[1]: https://storybook.js.org/docs/react/configure/sidebar-and-urls#generating-titles-based-on-__dirname

**Comment by tajo** [comment]
FYI: Storybook is also going to [require static titles](https://storybook.js.org/blog/storybook-on-demand-architecture/#:~:text=CSF%20titles%20and,) in the future because it's the only way how to support some critical features like automatic code-splitting (something that Ladle already does).

>  Tree structure based on actual file path

Some nesting based on file path can be achieved by using `--` in filenames:

https://www.ladle.dev/docs/stories#navigation-and-routes

> Any plan for this type of feature?

No.
